#!/bin/bash 
echo **********************************---**********************************
echo Hello In this script we will spin up 2 servers of 2 Service Providers:
echo 1. Digital Ocean
echo 2. Amazon Web Services
echo **********************************---**********************************
node do.js
node aws.js
echo Thank You :-) 
